language: node_js
node_js:
  - '11.14.0'

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | $(npm bin)/coveralls
